version: '3.8'

volumes:
  pg_data:
    driver: local

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://db_user:db_password@db:5432/db_name
      DEBUG: "on"
      ENVIRONMENT: development
      PYTHONUNBUFFERED: 1
    env_file:
      - ./.env.dev
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: library/postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
        POSTGRES_DB: db_name
        POSTGRES_USER: db_user
        POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
